name: Metrics

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 23 * * *
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: Kunamatata
          filename: metrics.classic.svg
          token: ${{ secrets.TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugin_languages: yes